nginx_user: "nginx"
nginx_service: "nginx"
nginx_pidfile_dir: "/var/run/nginx/"
nginx_worker_processes: "auto"
nginx_worker_connections: "1024"
nginx_multi_accept: "off"

nginx_log_format: |
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "75"
nginx_keepalive_requests: "600"

nginx_server_tokens: "off"
nginx_client_max_body_size: "64m"
nginx_server_names_hash_bucket_size: "64"

nginx_ssl_protocols: "TLSv1.2 TLSv1.3"
nginx_ssl_prefer_server_ciphers: "on"
nginx_ssl_ciphers: "HIGH:!aNULL:!MD5"

nginx_client_body_buffer_size: "16K"
nginx_client_header_buffer_size: "1K"
nginx_large_client_header_buffers: "2 1K"

nginx_config_dir: "/etc/nginx"
nginx_conf_file: "/etc/nginx/nginx.conf"
nginx_common_conf: "/etc/nginx/conf.d/common.conf"
nginx_security_conf: "/etc/nginx/conf.d/security.conf"
nginx_reverse_proxy_conf: "/etc/nginx/conf.d/reverse_proxy.conf"
nginx_mime_file_path: "/etc/nginx/mime.types"
nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main"
nginx_conf_path: "/etc/nginx/conf.d"
nginx_sites_available: "/etc/nginx/sites-available"
nginx_sites_enabled: "/etc/nginx/sites-enabled"
