---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
  when: security_fail2ban_enabled

- name: Copy Fail2Ban configuration
  template:
    src: "{{ fail2ban_config_template }}"
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: Restart fail2ban
  when: security_fail2ban_enabled
