---
- name: Configure Firewall
  import_tasks: firewall.yaml

- name: Configure Fail2Ban
  import_tasks: fail2ban.yaml

- name: Configure Auditd
  import_tasks: auditd.yaml

- name: Harden SSH
  import_tasks: ssh.yaml

- name: Configure Password Policies
  import_tasks: password_policies.yaml

- name: Enable Automatic Security Updates
  import_tasks: updates.yaml
