---
- name: Enable automatic security updates
  copy:
    dest: "{{ security_update_config_path }}"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
  when: security_auto_updates_enabled
